### ISSUE TITLE
BUG: Go back button not working in case of 404 error.

### ISSUE THREAD

**Issue by SahilSingh177** [IBM/carbon-ui-builder#160]
# Issue:
 On clicking go back button that appears in case of 404 error it doesn't redirects.

https://user-images.githubusercontent.com/96344003/195727882-ff9d6837-d9db-4c8a-adea-758acaf166cc.mov

**Comment by zvonimirfras** [comment]
Thanks for bringing this up, Sahil (@SahilSingh177)!

Better question is **why does it even error** in the first place??

Clicking "Templates only" filters the existing fragment list to show only the ones that are labelled "template".
This means _you're not leaving the page and there's nowhere to go back to_ (because you're still at the same page)

Workaround is to refresh the page - the infamous "have you tried turning it off and on again".

Do you mind sharing if there's **any errors reported to the dev console?**

**Comment by Rafajrg21** [comment]
Hi @zvonimirfras @SahilSingh177, I saw this bug as well and I replicated it, I also figured out what the problem was, can you assign this issue to me? I will attach the PR with the reason of why this failed and how I fixed it if that's ok :)

**Comment by zvonimirfras** [comment]
That's great, @Rafajrg21! Thanks for taking this on!
